spring:
  application:
    name: jwt-auth-demo
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_auth?useSSL=false&serverTimezone=UTC
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
#      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true